name: iOS project Run Tests

on:
  push:
    branches: [ Development ]

concurrency:
  group: build-ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Xcode_Tests:
    if: "!contains(github.event.head_commit.message, '#TestFlight')"
    runs-on: macos-latest
    environment: development

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
                ${{ runner.os }}-pods-

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Bundle dependencies
      run: bundle install

    - name: CocoaPods dependencies
      env: # Or as an environment variable
        tmdb_apiKey: ${{ secrets.TMDB_APIKEY }}
        ShipBook_appId: ${{ secrets.SHIPBOOK_APPID }}
        ShipBook_appKey: ${{ secrets.SHIPBOOK_APPKEY }}
        kkid_apikey: ${{ secrets.KKID_APIKEY }}
      run: bundle exec pod check || bundle exec pod install

    - name: CocoaPods Keys
      run: bundle exec pod keys list "KKid.xcodeproj"

    - name: CocoaPods Update
      if: "contains(github.event.head_commit.message, '#pod update')"
      run: bundle exec pod update

    - name: Run tests
      run: bundle exec fastlane test

  TestFlight:
    if: "contains(github.event.head_commit.message, '#TestFlight')"
    runs-on: macos-latest
    environment: Apple App Store

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: podcache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
                ${{ runner.os }}-pods-

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Bundle dependencies
      run: bundle install

    - name: CocoaPods dependencies
      env:
        tmdb_apiKey: ${{ secrets.TMDB_APIKEY }}
        ShipBook_appId: ${{ secrets.SHIPBOOK_APPID }}
        ShipBook_appKey: ${{ secrets.SHIPBOOK_APPKEY }}
        kkid_apikey: ${{ secrets.KKID_APIKEY }}
      run: bundle exec pod check || bundle exec pod install

    - name: CocoaPods Update
      if: "contains(github.event.head_commit.message, '#pod update')"
      run: bundle exec pod update

    - name: Fastlane Match
      env: # Or as an environment variable
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_USER: "jakumpe@justinkumpe.net"
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        MATCH_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      run: bundle exec fastlane matchget

    - name: Upload To TestFlight
      if: "contains(github.event.head_commit.message, '#TestFlight')"
      env: # Or as an environment variable
        APPLE_APPSTORE_API_ISSUER_ID: ${{ secrets.APPLE_APPSTORE_API_ISSUER_ID }}
        APPLE_APP_STORE_API_KEY: ${{ secrets.APPLE_APP_STORE_API_KEY }}
        APPLE_APP_STORE_API_KEY_ID: ${{ secrets.APPLE_APP_STORE_API_KEY_ID }}
      run: bundle exec fastlane beta

    - name: Commit and Push
      run: git commit ./KKid.xcodeproj ./KKid/Info.plist KKidUITests/Info.plist ./fastlane/ -m "Updated Fastfile" && git push